/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.halohoop.javalibraryjarkotlin2

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
